# ---------- used by Deployment ----------
nameOverride: frontend
image:
  repository: stagingacr010.azurecr.io/frontend   # your ACR image
  tag: "staging"
  pullPolicy: Always

replicaCount: 1

# nginx serves on 80; Deployment’s containerPort is tied to service.port in the default scaffold
# liveness/readiness hit "/" on the named port "http"
# livenessProbe:
#   httpGet: { path: "/", port: http }
# readinessProbe:
#   httpGet: { path: "/", port: http }

# --- PROBES (Deployment consumes these) ---
livenessProbe:
  httpGet:
    path: /            # or /healthz if you added that file in the image
    port: http         # matches the named port in your template
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /            # or /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

# land on userpool (AKS)
nodeSelector:
  kubernetes.azure.com/agentpool: userpool

#resources:
#  requests: { cpu: "100m", memory: "128Mi" }
#  limits:   { cpu: "500m", memory: "512Mi" }

# ---------- used by Service (and Ingress) ----------
service:
  type: ClusterIP   # because you have ingress-nginx in front
  port: 80          # IMPORTANT: matches nginx’s 80 inside the pod
  # targetPort: 80  # (leave out; the template uses the named port "http")

# ---------- used by Ingress ----------
ingress:
  enabled: true
  className: nginx
  # annotations:
  #   nginx.ingress.kubernetes.io/server-snippet: |
  #     location = /healthz {
  #       return 200 'ok';
  #       add_header Content-Type text/plain;
  #     }

  hosts:
    - host: frontend-staging.172.185.37.43.sslip.io
      paths:
        - path: /
          pathType: Prefix


