# ---------- used by Deployment ----------
nameOverride: frontend
image:
  repository: stagingacr02.azurecr.io/frontend
  tag: "d8f469d"
  pullPolicy: Always
replicaCount: 2
# --- PROBES ---
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
nodeSelector:
  kubernetes.azure.com/agentpool: userpool
# ---------- Service ----------
service:
  type: ClusterIP
  port: 80
# ---------- Ingress ----------
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: frontend-staging.172.185.27.61.sslip.io
      paths:
        # Frontend app
        - path: /
          pathType: Prefix
          backend:
            service:
              name: frontend-staging # IMPORTANT: Argo renames it to this
              port:
                number: 80
        # Product Service API
        - path: /api/products
          pathType: Prefix
          backend:
            service:
              name: product-staging-product-service
              port:
                number: 80
        # Contact Service API
        - path: /api/contact
          pathType: Prefix
          backend:
            service:
              name: contact-staging-contact-service
              port:
                number: 4001
