# ---------- used by Deployment ----------
nameOverride: product-service
image:
  repository: stagingacr010.azurecr.io/product-service   # your ACR image
  tag: "staging"
  pullPolicy: Always

replicaCount: 2

#  tell the container to listen on 4003
containerPort: 4003
env:
  - name: PORT
    value: "4003"


# --- PROBES (Deployment consumes these) ---
livenessProbe:
  httpGet:
    path: /            # or /healthz if you added that file in the image
    port: 4003          # matches the named port in your template
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /            # or /healthz
    port: 4003
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

# land on userpool (AKS)
nodeSelector:
  kubernetes.azure.com/agentpool: userpool


# ---------- used by Service (and Ingress) ----------
service:
  type: ClusterIP   # because you have ingress-nginx in front
  port: 80          # IMPORTANT: matches nginx’s 80 inside the pod
  targetPort: 4003  # map Service to the app's real port

# ---------- used by Ingress ----------
ingress:
  enabled: true
  className: nginx
  # annotations:
  #   nginx.ingress.kubernetes.io/server-snippet: |
  #     location = /healthz {
  #       return 200 'ok';
  #       add_header Content-Type text/plain;
  #     }

  hosts:
    - host: product-staging.172.185.37.43.sslip.io
      paths:
        - path: /
          pathType: Prefix


