# ---------- used by Deployment ----------
nameOverride: product-service
image:
  repository: stagingacr02.azurecr.io/product-service
  tag: "e9ea200"
  pullPolicy: Always
replicaCount: 2
# --- PROBES (Deployment consumes these) ---
livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3
readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3
# land on userpool (AKS)
nodeSelector:
  kubernetes.azure.com/agentpool: userpool
# --- service account override ---
serviceAccount:
  create: true
  name: "products-sa"
  automount: true
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: "f50d4e60-628e-40bf-9093-2d0002599583"
# ---------- used by Service (and Ingress) ----------
service:
  type: ClusterIP
  port: 80
# ---------- used by Ingress ----------
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
  hosts:
    - host: product-staging.172.185.27.61.sslip.io
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: product-staging-product-service
              port:
                number: 80
        - path: /api/products
          pathType: Prefix
          backend:
            service:
              name: product-staging-product-service
              port:
                number: 80
        - path: /api/products/uploads
          pathType: Prefix
          backend:
            service:
              name: product-staging-product-service
              port:
                number: 80
# --- CSI / Key Vault ---
csi:
  enabled: true
  secretProviderClass: "product-mongo-kv-conn"
# App config: non-sensitive env var with FILE PATH (not the secret)
env:
  - name: MONGO_URI_FILE
    value: "/mnt/secrets-store/product-mongo-connection"
# Mount the CSI volume that contains the secret file
volumeMounts:
  - name: secrets-store
    mountPath: /mnt/secrets-store
    readOnly: true
volumes:
  - name: secrets-store
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: product-mongo-kv-conn
