# ---------- used by Deployment ----------
nameOverride: product-service
image:
  repository: stagingacr010.azurecr.io/product-service   # your ACR image
  tag: "staging"
  pullPolicy: Always

replicaCount: 2


# --- PROBES (Deployment consumes these) ---
livenessProbe:
  httpGet:
    path: /            # or /healthz if you added that file in the image
    port: http          # matches the named port in your template
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /            # or /healthz
    port: http
  initialDelaySeconds: 3
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 3

# land on userpool (AKS)
nodeSelector:
  kubernetes.azure.com/agentpool: userpool

# --- service account override
serviceAccount:
  create: true
  name: "wi-sa"
  automount: true
  annotations:
    azure.workload.identity/use: "true"
    azure.workload.identity/client-id: "cd19c406-81db-4d8a-b307-b6cba48fbab4"

# ---------- used by Service (and Ingress) ----------
service:
  type: ClusterIP   # because you have ingress-nginx in front
  port: 80          # IMPORTANT: matches nginx’s 80 inside the pod
  # targetPort: 80  # map Service to the template

# ---------- used by Ingress ----------
ingress:
  enabled: true
  className: nginx
  # annotations:
  #   nginx.ingress.kubernetes.io/server-snippet: |
  #     location = /healthz {
  #       return 200 'ok';
  #       add_header Content-Type text/plain;
  #     }

  hosts:
    - host: product-staging.172.185.37.43.sslip.io
      paths:
        - path: /
          pathType: Prefix


