apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: product-mongo-kv-conn          # <-- NEW name
  namespace: makeup-staging
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6b73a742-087d-48b4-a0ec-b341d58d598d"   # same UAMI
    keyvaultName: "staging-kv02"                       # same KV
    tenantId: "82168e20-b2fb-4b5b-92ff-91df15b0de08"   # same tenant
    objects: |
      array:
        - |
          objectName: "mongo-connection"   # <-- KV secret name from Terraform
          objectType: secret
          objectVersion: ""
  # secretObjects:
  #   - secretName: product-mongo-conn      # <-- NEW K8s Secret for Mongo
  #     type: Opaque
  #     data:
  #       - objectName: "mongo-connection"
  #         key: connectionString           # key inside the K8s Secret
